[tool.poetry]
name = "learn-zeromq"
version = "0.1.0"
description = ""
authors = ["Ahmad Alfan <aalf4nz@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pyzmq = "^25.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
